name: Terraform CI

on:
  pull_request:
    paths:
      - "environments/**"
      - "modules/**"
      - ".github/workflows/**"

  push:
    branches:
      - main
    paths:
      - "environments/**"
      - "modules/**"
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive ../..

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: "1"